Object Creation

Creating a series by passing a list of values,letting panda create default Range Index

In [8]:

import numpy as np
import pandas as pd

In [9]:
s = pd.Series([1,3,5, np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a dataframe by passing a numpy array with a datetime index using date_range() and labeled columns.

In [10]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [11]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.396151  2.014339 -0.459879  1.018157
2013-01-02  1.658322  0.902785 -0.079600  0.607789
2013-01-03  0.097010 -1.830312 -0.659378  1.483496
2013-01-04 -0.335893 -0.579585 -1.004141 -0.426638
2013-01-05 -0.794192  0.750310  0.043921 -1.474908
2013-01-06  0.388137  0.109297 -0.841985  0.161173

Creating a dataframe by passings a dictionary of objects where the keys are the column lables and the vlaues are the column values.

In [12]:
df2 = pd.DataFrame(
    {
        "A":1.0,
        "B":pd.Timestamp("20130102"),
        "C":pd.Series(1, index=list(range(4)),dtype="float32"),
        "D":np.array([3]*4,dtype="int32"),
        "E":pd.Categorical(["test","train","test","train"]),
        "F":"foo",

    }
)

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of the resulting dtataframe have different dtypes

In [14]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

If you're using IPython, tab completion for column names(as well as public attributes)is automatically enabled.Here's subset of the attributes that will be completed:

In [12]:df2.<TAB> #noqa:E225, E999

df2.A
df2.abs
df2.add_prefix
df2.add_suffix
df2.align
df2.all
df2.any
df2.append
df2.append
df2.apply
df2.B
df2.diff

df2.bool
df2.boxplot
df2.C
df2.clip
df2.count
df2.copy
df2.combine
df2.describe
df2.duplicated

As you can see, the columns A , B, C , D are automatically tab completed. E and F are there as well; the rest of the attributes have been truncated for brevity

Viewing data

Use dataframe.head() and dataframe.tail() to view the top and bottom rows of the frame respectively:

In [17]:
df2.head(2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo

In [18]:
df2.tail(2)

     A          B    C  D      E    F
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Display the DataFrame.index or DataFrame.columns():

In [22]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [23]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

Return a NumPy represrntation of the underlying with DataFrame.to_numpy() without the index or column labels:

In [29]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

describe() shows a quick statisic summary of your data:

In [30]:
df2.describe()

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2013-01-02 00:00:00  1.0  3.0
min    1.0  2013-01-02 00:00:00  1.0  3.0
25%    1.0  2013-01-02 00:00:00  1.0  3.0
50%    1.0  2013-01-02 00:00:00  1.0  3.0
75%    1.0  2013-01-02 00:00:00  1.0  3.0
max    1.0  2013-01-02 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

Transposing your data:

In [31]:
df2.T

,0,1,2,3
A,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,train,test,train
F,foo,foo,foo,foo

DataFrame.sort_index() sorts by an axis:

In [32]:
df2.sort_index(axis=1, ascending=False)

     F      E  D    C          B    A
0  foo   test  3  1.0 2013-01-02  1.0
1  foo  train  3  1.0 2013-01-02  1.0
2  foo   test  3  1.0 2013-01-02  1.0
3  foo  train  3  1.0 2013-01-02  1.0

DataFrame.sort_values() sorts by values:

In [33]:
df2.sort_values(by="B")

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [38]:
df.iloc()

Getitem([])

For a dataFrame, passing a single label selects a column and yields a series:

In [40]:
df2["A"]

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

If the label only containes letter, numbers, and ubderscores, you can alternatively use the column name attribute:

In [42]:
df2.A

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

Passing alist of column labels selects multiple columns, which can be useful for getting a subset/rearranging:

In [44]:
df2[['B',"A"]]

           B    A
0 2013-01-02  1.0
1 2013-01-02  1.0
2 2013-01-02  1.0
3 2013-01-02  1.0

For a DataFrame, passing a slice: selects matching row:

In [46]:
df2[1:3]

     A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo

Selection by label

see more in Selection by label using DataFrame.loc() or DataFrame.at().

Selecting a row matching a label:

In [49]:
df2.loc[[0]]

     A          B    C  D     E    F
0  1.0 2013-01-02  1.0  3  test  foo

Selecting all rows (:) with a select column labels

In [50]:
df.loc[:,["A","B"]]

                   A         B
2013-01-01 -0.396151  2.014339
2013-01-02  1.658322  0.902785
2013-01-03  0.097010 -1.830312
2013-01-04 -0.335893 -0.579585
2013-01-05 -0.794192  0.750310
2013-01-06  0.388137  0.109297

For label slicing, both endpoints are include:

In [52]:
df.loc["20130103":"20130104",["A","B"]]

                   A         B
2013-01-03  0.097010 -1.830312
2013-01-04 -0.335893 -0.579585

Selecting a single row and column label returns a scaler:

In [55]:
df.loc[dates[0],"A"]

np.float64(-0.3961507355425335)

For getting fast access to a scaler(equivalent to the prior method)

In [56]:
df.at[dates[0],"A"]

np.float64(-0.3961507355425335)

Selection by position

Select via the position of the passed integers:

In [60]:
df2.iloc[2]

A                    1.0
B    2013-01-02 00:00:00
C                    1.0
D                      3
E                   test
F                    foo
Name: 2, dtype: object

integer slice acts similar to NumPy/Python

In [62]:
df2.iloc[3:2,0:2]

Empty DataFrame
Columns: [A, B]
Index: []