A Series is a one_dimensional labled Array

In [1]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

Creating a series with custom Index

In [2]:
import pandas as pd

s=pd.Series([90,85,95], index = ["Math","Science","English"])
print(s)

Math       90
Science    85
English    95
dtype: int64

Acess data:

In [3]:
print(s["Math"])

90

A DataFram is a 2-dimensional table (rows and columns)

In [4]:
# Create a DataFrame

import pandas as pd

data = {

   "Name":["Guddiya","Aman","Riya"],
   "Age":[22,23,21],
   "city":["Delhi","Mumbai","Pune"]
}
df = pd.DataFrame(data)
print(df)

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [5]:
# Access a column

print(df["Name"])

0    Guddiya
1       Aman
2       Riya
Name: Name, dtype: str

In [6]:
# Access rows

# Using.loc[]

print(df.loc[0])

Name    Guddiya
Age          22
city      Delhi
Name: 0, dtype: object

In [7]:
# Using .iloc[]
print(df.iloc[1])

Name      Aman
Age         23
city    Mumbai
Name: 1, dtype: object

Basic Information

In [8]:
print(df.head())

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [9]:
print(df.tail())

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [10]:
print(df.shape)

(3, 3)

In [11]:
print(df.columns)

Index(['Name', 'Age', 'city'], dtype='str')

In [12]:
print(df.dtypes)

Name      str
Age     int64
city      str
dtype: object

In [13]:
# Series
## A panda series is a 1_diemensional array like object that can hold any data 
import pandas as pd
 
data =[1,2,3,4,5] 
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [14]:
## Create a series from dictionary
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [15]:
data = [1,2,3,4,5]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
# DataFrame
## create a dataFrame from a Dictionary

data={
    "Name":['krish','jhon','jack'],
     "Age":[20,25,30],
     "city":['Ranchi',"Delhi","pune"]
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    city
0  krish   20  Ranchi
1   jhon   25   Delhi
2   jack   30    pune
<class 'pandas.DataFrame'>

In [17]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.head(5))

   Order_ID  Order_Date        Category   Price  Quantity  Customer_Rating  \
0  ORD-1000  2025-01-01        Clothing  352.10         1              4.0
1  ORD-1001  2025-01-02             NaN  272.69         2              4.0
2  ORD-1002  2025-01-03  Home & Kitchen  161.67         3              1.0
3  ORD-1003  2025-01-04        Clothing  408.76         2              3.0
4  ORD-1004  2025-01-05     Electronics  345.52         3              4.0

     Payment_Method
0  Cash on Delivery
1               UPI
2               UPI
3               UPI
4  Cash on Delivery

In [18]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.tail(5))

     Order_ID  Order_Date     Category   Price  Quantity  Customer_Rating  \
495  ORD-1495  2026-05-11     Clothing   54.88         2              4.0
496  ORD-1496  2026-05-12     Clothing  459.48         2              NaN
497  ORD-1497  2026-05-13  Electronics   77.04         1              2.0
498  ORD-1498  2026-05-14          NaN  475.62         1              2.0
499  ORD-1499  2026-05-15          NaN  228.54         3              3.0

       Payment_Method
495       Credit Card
496               UPI
497  Cash on Delivery
498       Credit Card
499       Credit Card

In [19]:
# Accessing Data From DataFrame 
data

{'Name': ['krish', 'jhon', 'jack'],
 'Age': [20, 25, 30],
 'city': ['Ranchi', 'Delhi', 'pune']}

In [20]:
type(df['Name'])
df['Name']

KeyError: 'Name'

In [ ]:
df.loc[0]

Name     krish
Age         20
city    Ranchi
Name: 0, dtype: str

In [ ]:
df.iloc[1]

Name     jhon
Age        25
city    Delhi
Name: 1, dtype: str

In [ ]:
## Accessing a specified element
df.at[2,'Age']

'30'

In [ ]:
df.at[1,'Name']

'jhon'

In [ ]:
## Data manipulation with DataFram
df

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [ ]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

      Name  Age    city  Salary
0  Guddiya   22   Delhi   50000
1     Aman   23  Mumbai   60000
2     Riya   21    Pune   70000

In [ ]:
## Remove a column
df.drop("Salary",axis=1,inplace=True)
df

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [ ]:
## Add age the column 
df['Age']=df['Age']+1
df

      Name  Age    city
0  Guddiya   23   Delhi
1     Aman   24  Mumbai
2     Riya   22    Pune

In [ ]:
# If i want to remove row
df.drop([0],inplace=True)
df

   Name  Age    city
1  Aman   24  Mumbai
2  Riya   22    Pune

In [ ]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.head(5))
df

   Order_ID  Order_Date        Category   Price  Quantity  Customer_Rating  \
0  ORD-1000  2025-01-01        Clothing  352.10         1              4.0
1  ORD-1001  2025-01-02             NaN  272.69         2              4.0
2  ORD-1002  2025-01-03  Home & Kitchen  161.67         3              1.0
3  ORD-1003  2025-01-04        Clothing  408.76         2              3.0
4  ORD-1004  2025-01-05     Electronics  345.52         3              4.0

     Payment_Method
0  Cash on Delivery
1               UPI
2               UPI
3               UPI
4  Cash on Delivery

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery
...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card

In [ ]:
# Display the data types of each column
print("Data types \n:",df.dtypes)

# Discribe the DataFrame
print("Statistical summary:\n", df.describe())
# Group by a column and perform aggregation
grouped = df.groupby('Category')['Value'].mean()
print("Mean value by category\n:",grouped)

Data types
: Order_ID               str
Order_Date             str
Category               str
Price              float64
Quantity             int64
Customer_Rating    float64
Payment_Method         str
dtype: object
Statistical summary:
             Price    Quantity  Customer_Rating
count  494.000000  500.000000       457.000000
mean   246.424777    3.092000         3.619256
std    139.640181   10.748702         1.111888
min     12.270000    1.000000         1.000000
25%    122.555000    1.000000         3.000000
50%    241.775000    2.000000         4.000000
75%    365.600000    3.000000         4.000000
max    499.860000  100.000000         5.000000

KeyError: 'Column not found: Value'

In [ ]:
import pandas as pd

data1 = {
    "Name":["Guddiya","Aman","Riya","Rahul"],
    "Age":[22,23,21,24],
    "Marks":[90,85,95,80],
    "City":["Delhi","Mumbai","Pune","Delhi"]
}
df = pd.DataFrame(data1)
df

      Name  Age  Marks    City
0  Guddiya   22     90   Delhi
1     Aman   23     85  Mumbai
2     Riya   21     95    Pune
3    Rahul   24     80   Delhi

In [ ]:
# Select column

print(df[["Name"]])

      Name
0  Guddiya
1     Aman
2     Riya
3    Rahul

In [ ]:
# 2. Select Multiple Columns
print(df[["Name","Marks"]])

      Name  Marks
0  Guddiya     90
1     Aman     85
2     Riya     95
3    Rahul     80

In [ ]:
# 3.Add a New column
df["Passed"]=True
df

      Name  Age  Marks    City  Passed
0  Guddiya   22     90   Delhi    True
1     Aman   23     85  Mumbai    True
2     Riya   21     95    Pune    True
3    Rahul   24     80   Delhi    True

In [ ]:
# 4. Update a Column

# INcrease everyday's age by 1
df["Age"]+=1
df

      Name  Age  Marks    City  Passed
0  Guddiya   23     90   Delhi    True
1     Aman   24     85  Mumbai    True
2     Riya   22     95    Pune    True
3    Rahul   25     80   Delhi    True

In [ ]:
# Delete Column
df.drop("City",axis=1,inplace=True)
df

      Name  Age  Marks  Passed
0  Guddiya   23     90    True
1     Aman   24     85    True
2     Riya   22     95    True
3    Rahul   25     80    True

In [ ]:
# Delete a Row
# Delete row with index 2.

df.drop(2, axis=0, inplace=True)
df

      Name  Age  Marks  Passed
0  Guddiya   23     90    True
1     Aman   24     85    True
3    Rahul   25     80    True

In [ ]:
# 7.Rename columns
df.rename(columns ={ "Marks":"Scores"}, inplace = True)
df

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

In [ ]:
# Filter Data
# Students with marks greater then 85.

print(df[df["Scores"] > 85])

      Name  Age  Scores  Passed
0  Guddiya   23      90    True

In [ ]:
#9.
#  Multiple conditions

print(df[(df["Scores"] > 80) & (df["Name"] == "Guddiya")])

      Name  Age  Scores  Passed
0  Guddiya   23      90    True

10. Short Data

In [ ]:
# Accending
print(df.sort_values(by="Scores"))

      Name  Age  Scores  Passed
3    Rahul   25      80    True
1     Aman   24      85    True
0  Guddiya   23      90    True

In [ ]:
# Descending order

print(df.sort_values(by="Scores",ascending=False))

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

11. Find Missing values

In [ ]:
print(df.isnull())

    Name    Age  Scores  Passed
0  False  False   False   False
1  False  False   False   False
3  False  False   False   False

In [ ]:
print(df.isnull().sum())

Name      0
Age       0
Scores    0
Passed    0
dtype: int64

12. Fill Missing Values

In [ ]:
# df.fillna(0)

In [ ]:
print(df["Scores"].fillna(df["Scores"].mean(),inplace=True))

0    90
1    85
3    80
Name: Scores, dtype: int64

/tmp/ipykernel_4505/3322902417.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  print(df["Scores"].fillna(df["Scores"].mean(),inplace=True))

13. Remove missing value

In [ ]:
# df.dropna()

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

14. change Data Type

In [ ]:
df["Age"]=df["Age"].astype(float)
df

      Name   Age  Scores  Passed
0  Guddiya  23.0      90    True
1     Aman  24.0      85    True
3    Rahul  25.0      80    True

15. Create a new column

In [ ]:
df["Bonus"] = df["Scores"]+5
df

      Name   Age  Scores  Passed  Bonus
0  Guddiya  23.0      90    True     95
1     Aman  24.0      85    True     90
3    Rahul  25.0      80    True     85

16. Apply a function

In [ ]:
df["Scores"]=df["Scores"].apply(lambda x:x+5)
df

      Name   Age  Scores  Passed  Bonus
0  Guddiya  23.0     100    True     95
1     Aman  24.0      95    True     90
3    Rahul  25.0      90    True     85

17. GROUP DATA
    average marks data

In [ ]:
print(df.groupby("Bonus")["Scores"].mean())

Bonus
85     90.0
90     95.0
95    100.0
Name: Scores, dtype: float64

18. Remove Duplicates

In [ ]:
df.drop.duplicates()

19. Reset INdex

In [ ]:
print(df.reset_index(drop=True, inplace=True))

None

20. Save DataFrame

In [ ]:
#  CSV:

print(df.to_csv("students.csv", index=False))

None

In [ ]:
# Excel:
print(df.to_excel("students.xlsx", index=False))

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('ecommerce_orders.csv')
# fetch the five rows
df.head(5)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery

In [ ]:
df.tail(5)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card

In [ ]:
df.describe()

            Price    Quantity  Customer_Rating
count  494.000000  500.000000       457.000000
mean   246.424777    3.092000         3.619256
std    139.640181   10.748702         1.111888
min     12.270000    1.000000         1.000000
25%    122.555000    1.000000         3.000000
50%    241.775000    2.000000         4.000000
75%    365.600000    3.000000         4.000000
max    499.860000  100.000000         5.000000

In [ ]:
df.dtypes

Order_ID               str
Order_Date             str
Category               str
Price              float64
Quantity             int64
Customer_Rating    float64
Payment_Method         str
dtype: object

In [ ]:
## Handling Missing value
df.isnull()

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False
496,False,False,False,False,False,True,False
497,False,False,False,False,False,False,False
498,False,False,True,False,False,False,False
499,False,False,True,False,False,False,False

In [ ]:
df[df.isnull()]

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().any(axis=1)

0      False
1       True
2      False
3      False
4      False
       ...
495    False
496     True
497    False
498     True
499     True
Length: 500, dtype: bool

In [ ]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Category           29
Price               6
Quantity            0
Customer_Rating    43
Payment_Method      0
dtype: int64

In [ ]:
df.fillna(0)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,0,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery
...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,0.0,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,0,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,0,228.54,3,3.0,Credit Card

Filling missing value with mean of the column

In [ ]:
df['Customer_FiLLna']=df['Customer_Rating'].fillna(df['Customer_Rating'].mean())
df

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.000000
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.000000
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.000000
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.000000
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.000000
...,...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card,4.000000
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI,3.619256
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery,2.000000
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card,2.000000
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card,3.000000

In [ ]:

# Renaming columns

df = df.rename(columns={'Order_Date':'Sales Date'})
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0

In [ ]:
## Change datatypes
df['Quantity_new']=df['Quantity'].astype(float)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0

In [ ]:
# df['Quantity_new'] =df['Quantity'].fillna(df['Quantity'].mean()).astype(int)
df['Quantity_new']=df['Quantity'].astype(float)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0

In [ ]:
df['New_Price'] = df['Price'].apply(lambda x:x*2)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new,New_Order_ID,New_Price
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0,ORD-1000ORD-1000,704.20
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0,ORD-1001ORD-1001,545.38
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0,ORD-1002ORD-1002,323.34
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0,ORD-1003ORD-1003,817.52
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0,ORD-1004ORD-1004,691.04

In [ ]:
grouped_mean = df.groupby('Category')['Price'].mean()
print(grouped_mean)

Category
Books             234.104800
Clothing          256.360662
Electronics       238.445000
Home & Kitchen    254.265392
Name: Price, dtype: float64

In [ ]:
grouped_sum = df.groupby(['Category','Order_ID'])['Price'].sum()
print(grouped_sum)

Category        Order_ID
Books           ORD-1007    413.04
                ORD-1033    282.16
                ORD-1035    472.94
                ORD-1043    339.13
                ORD-1052    280.43
                             ...
Home & Kitchen  ORD-1462    130.22
                ORD-1480    173.78
                ORD-1481    387.75
                ORD-1483     46.82
                ORD-1491    350.40
Name: Price, Length: 469, dtype: float64

In [ ]:
## Aggregate multiple function
grouped_agg = df.groupby('Order_ID')['Price'].agg(['mean','sum','count'])
print(grouped_agg)

            mean     sum  count
Order_ID
ORD-1000  352.10  352.10      1
ORD-1001  272.69  272.69      1
ORD-1002  161.67  161.67      1
ORD-1003  408.76  408.76      1
ORD-1004  345.52  345.52      1
...          ...     ...    ...
ORD-1495   54.88   54.88      1
ORD-1496  459.48  459.48      1
ORD-1497   77.04   77.04      1
ORD-1498  475.62  475.62      1
ORD-1499  228.54  228.54      1

[498 rows x 3 columns]

In [ ]:
# Merging and joining Dataframes
# Create sample DataFrames

df1 = pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','C'],'Vale2':[4,5,6]})

In [ ]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [ ]:
df2

  key  Vale2
0   A      4
1   B      5
2   C      6

* Aggrigate functions

In [ ]:
import pandas as pd

data = {
    'Name':["Guddiya","Aman","Rahul","Riya"],
    'Marks':[90,85,95,80],
    'Age':[21,23,22,24]
}
df = pd.DataFrame(data)
print(df)

      Name  Marks  Age
0  Guddiya     90   21
1     Aman     85   23
2    Rahul     95   22
3     Riya     80   24

In [ ]:
# 1. sum
print(df['Marks'].sum())

350

In [ ]:
# 2.Mean Average
print(df["Marks"].mean())

87.5

In [ ]:
# 3.Maximum
print(df["Marks"].max())

95

In [ ]:
# 4.Minimum
print(df["Marks"].min())

80

In [ ]:
#5.count
print(df["Marks"].count())

4

In [ ]:
# 6. Standard Deviation
# measures how spread out the values are.
print(df["Marks"].std())

6.454972243679028

In [ ]:
# 7. Variance

print(df["Marks"].var())

41.666666666666664

In [ ]:
# 8.Median
# The middle value after sorting
print(df["Marks"].median())

87.5

In [ ]:
# 9.Mode
# The most frequently occuring value.
print(df["Marks"].mode())

0    80
1    85
2    90
3    95
Name: Marks, dtype: int64

In [ ]:
marks = [80,90,90,85]
print(pd.Series(marks).mode())

0    90
dtype: int64

In [ ]:
# 10. Multiple aggrigret Function

print(df['Marks'].agg(['sum','mean','max','min']))

sum     350.0
mean     87.5
max      95.0
min      80.0
Name: Marks, dtype: float64

Agrrigrant functios with groupby()

In [ ]:
data = {
    "Department": ['IT','IT','HR','HR'],
    "Salary":[400000,450000,50000,4500]
}

df = pd.DataFrame(data)
print(df)

  Department  Salary
0         IT  400000
1         IT  450000
2         HR   50000
3         HR    4500

In [ ]:
# Average Salary by depatment
print(df.groupby('Department')['Salary'].mean())

Department
HR     27250.0
IT    425000.0
Name: Salary, dtype: float64

In [ ]:
#  Multiple Aggregate Functions
print(df.groupby('Department')['Salary'].agg(["mean","sum","max","min"]))

                mean     sum     max     min
Department
HR           27250.0   54500   50000    4500
IT          425000.0  850000  450000  400000

In [ ]:
#  described() uses Aggregate functions
print(df.describe())

              Salary
count       4.000000
mean   226125.000000
std    231293.599494
min      4500.000000
25%     38625.000000
50%    225000.000000
75%    412500.000000
max    450000.000000

In [ ]:
import pandas as pd

df = pd.read_csv('students_data.csv')
print(df.head())

   Student_ID     Name Department  Age  Marks  Attendance       City
0         101  Guddiya         IT   22     90          95      Delhi
1         102     Aman         IT   23     85          88     Mumbai
2         103     Riya         HR   21     95          97       Pune
3         104    Rahul    Finance   24     80          85      Delhi
4         105    Priya         IT   22     75          92  Bangalore

In [ ]:
print(df['Marks'].apply(lambda x:x+2))

In [ ]:
df.groupby('Department')['Marks'].max()

Department
Finance    96
HR         95
IT         90
Name: Marks, dtype: int64

In [ ]:
# The student with the maximum marks.
top_student=df.loc[[df["Marks"].idxmax()]]
print(top_student)

    Student_ID   Name Department  Age  Marks  Attendance  City
14         115  Meera    Finance   21     96          99  Pune

In [ ]:
print(df.loc[[df['Marks'].idxmin()]])

   Student_ID   Name Department  Age  Marks  Attendance       City
4         105  Priya         IT   22     75          92  Bangalore

In [ ]:
print(df.loc[df["Marks"].idxmax(),["Name","Marks"]])

Name     Meera
Marks       96
Name: 14, dtype: object

In [ ]:
print(df.loc[df['Attendance'].idxmax(),["Name","Attendance"]])

Name          Meera
Attendance       99
Name: 14, dtype: object

In [ ]:
print(df.loc[df['Attendance'].idxmin(),["Name","Attendance"]])

Name          Karan
Attendance       80
Name: 7, dtype: object

In [ ]:
# the top 3 students by marks

top3 =df.nlargest(3,'Marks')[["Name","Marks"]]
print(top3)

     Name  Marks
14  Meera     96
2    Riya     95
9   Vikas     93

In [ ]:
top5 = df.nlargest(5,'Marks')[["Name","Marks"]]
print(top5)

       Name  Marks
14    Meera     96
2      Riya     95
9     Vikas     93
6    Anjali     91
0   Guddiya     90

In [ ]:
top2_it = df[df['Department']=='IT'].nlargest(2,'Marks')
print(top2_it)

    Student_ID     Name Department  Age  Marks  Attendance   City
0          101  Guddiya         IT   22     90          95  Delhi
10         111    Sneha         IT   21     87          91   Pune

In [ ]:
top3_hr = df[df['Department']=='HR'].nlargest(3,"Marks")
print(top3_hr)

    Student_ID   Name Department  Age  Marks  Attendance       City
2          103   Riya         HR   21     95          97       Pune
12         113  Pooja         HR   22     89          94  Bangalore
5          106  Rohit         HR   23     88          90     Mumbai

In [ ]:
top_Fin = df[df['Department']=='Finance'][['Marks','Name']].max()
print(top_Fin)

Marks       96
Name     Vikas
dtype: object

In [ ]:
import pandas as pd

from io import StringIO
Data ='{"employee_name":"james","email":"james@gmail.com","job_profile":[{"title1":"Team leader"}]}'
df=pd.read_json(StringIO(Data))

In [ ]:
df

  employee_name            email                job_profile
0         james  james@gmail.com  {'title1': 'Team leader'}

In [ ]:
df.to_json()

'{"employee_name":{"0":"james"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team leader"}}}'

In [ ]:
df.to_json(orient='index')

'{"0":{"employee_name":"james","email":"james@gmail.com","job_profile":{"title1":"Team leader"}}}'

In [ ]:
df.to_json(orient='records')

'[{"employee_name":"james","email":"james@gmail.com","job_profile":{"title1":"Team leader"}}]'

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df.head()

   Student_ID     Name Department  Age  Marks  Attendance       City
0         101  Guddiya         IT   22     90          95      Delhi
1         102     Aman         IT   23     85          88     Mumbai
2         103     Riya         HR   21     95          97       Pune
3         104    Rahul    Finance   24     80          85      Delhi
4         105    Priya         IT   22     75          92  Bangalore

In [ ]:
df.to_csv("wine.csv")

In [ ]:
pip install lxml

Requirement already satisfied: lxml in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (6.1.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: html5lib in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from beautifulsoup4) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from beautifulsoup4) (4.15.0)

In [ ]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"
pd.read_html(url)

[                                            Bank Name               City  \
 0                                 Small Business Bank             Lenexa
 1       Kentland Federal Savings and Loan Association           Kentland
 2             Community Bank and Trust - West Georgia           LaGrange
 3                   Metropolitan Capital Bank & Trust            Chicago
 4                        The Santa Anna National Bank         Santa Anna
 5                                Pulaski Savings Bank            Chicago
 6                  The First National Bank of Lindsay            Lindsay
 7               Republic First Bank dba Republic Bank       Philadelphia
 8                                       Citizens Bank           Sac City
 9                            Heartland Tri-State Bank            Elkhart
 10                                First Republic Bank      San Francisco
 11                                     Signature Bank           New York
 12                                Silicon Valley Bank        Santa Clara
 13                                  Almena State Bank             Almena
 14                         First City Bank of Florida  Fort Walton Beach
 15                               The First State Bank      Barboursville
 16                                 Ericson State Bank            Ericson
 17                   City National Bank of New Jersey             Newark
 18                                      Resolute Bank             Maumee
 19                              Louisa Community Bank             Louisa
 20                               The Enloe State Bank             Cooper
 21                Washington Federal Bank for Savings            Chicago
 22    The Farmers and Merchants State Bank of Argonia            Argonia
 23                                Fayette County Bank         Saint Elmo
 24  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...          Milwaukee

             State   Cert                     Acquiring Institution  \
 0          Kansas  25744  The Farmers State Bank of Oakley, Kansas
 1         Indiana  28722                             Kentland Bank
 2         Georgia  25796                               Anchor Bank
 3        Illinois  57488                   First Independence Bank
 4           Texas   5520                 Coleman County State Bank
 5        Illinois  28611                           Millennium Bank
 6        Oklahoma   4134                    First Bank & Trust Co.
 7    Pennsylvania  27332         Fulton Bank, National Association
 8            Iowa   8758                 Iowa Trust & Savings Bank
 9          Kansas  25851                    Dream First Bank, N.A.
 10     California  59017                 JPMorgan Chase Bank, N.A.
 11       New York  57053                       Flagstar Bank, N.A.
 12     California  24735       First–Citizens Bank & Trust Company
 13         Kansas  15426                               Equity Bank
 14        Florida  16748                 United Fidelity Bank, fsb
 15  West Virginia  14361                            MVB Bank, Inc.
 16       Nebraska  18265                Farmers and Merchants Bank
 17     New Jersey  21111                           Industrial Bank
 18           Ohio  58317                        Buckeye State Bank
 19       Kentucky  58112         Kentucky Farmers Bank Corporation
 20          Texas  10716                        Legend Bank, N. A.
 21       Illinois  30570                        Royal Savings Bank
 22         Kansas  17719                               Conway Bank
 23       Illinois   1802                 United Fidelity Bank, fsb
 24      Wisconsin  30003       First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       July 17, 2026                 10553
 1       July 10, 2026                 10552
 2         May 1, 2026                 10551
 3    January 30, 2026                 10550
 4       June 27, 2025                 10549
 5    January 17, 2025                 10548
 6    October 18, 2024                 10547
 7      April 26, 2024                 10546
 8    November 3, 2023                 10545
 9       July 28, 2023                 10544
 10        May 1, 2023                 10543
 11     March 12, 2023                 10540
 12     March 10, 2023                 10539
 13   October 23, 2020                 10538
 14   October 16, 2020                 10537
 15      April 3, 2020                 10536
 16  February 14, 2020                 10535
 17   November 1, 2019                 10534
 18   October 25, 2019                 10533
 19   October 25, 2019                 10532
 20       May 31, 2019                 10531
 21  December 15, 2017                 10530
 22   October 13, 2017                 10529
 23       May 26, 2017                 10528
 24        May 5, 2017                 10527  ]

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
url = "https://www.kaggle.com/datasets/spscientist/students-performance-in-exams"
df=pd.read_html(url)
df[0]

ValueError: No tables found

In [ ]:
url="https://en.wikipedia.org/wiki/List_of_mobile_network_operators"
pd.read_html(url)

HTTPError: HTTP Error 403: Forbidden

In [ ]:
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"


df

NameError: name 'df' is not defined

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Path to dataset files: /home/guddiya-singh/.cache/kagglehub/datasets/spscientist/students-performance-in-exams/versions/1

In [ ]:
pip install kagglehub

Requirement already satisfied: kagglehub in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglehub) (0.1.35)
Requirement already satisfied: packaging in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglehub) (4.70.0)
Requirement already satisfied: protobuf in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/guddiya-singh/Downloads/python-main-main/.venv/lib/python3.13/site-packages (from requests->kagglehub) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Path to dataset files: /home/guddiya-singh/.cache/kagglehub/datasets/spscientist/students-performance-in-exams/versions/1

In [ ]:
import pandas as pd

df = pd.read_csv("Students_Performance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
url="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url,match="Country",header=0)[0]

HTTPError: HTTP Error 403: Forbidden

In [ ]:
import pandas as pd

pd.read_excel("sample_data.xlsx")

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [ ]:
import os

print(os.path.exists("sample_data.xlsx"))

True

In [ ]:
import pandas as pd

df = pd.read_excel("sample_data.xlsx", engine="openpyxl")
with open('sample_data.xlsx','a') as file:
    file.write("Append operation taking place!\n")
print(df.head())

      Name  Age Department  Marks
0  Guddiya   22         IT     90
1     Aman   23         HR     85
2     Riya   21    Finance     95
3    Rahul   20         IT     88
4     Neha   21         HR     92

In [ ]:
# import pandas as pd

# data = {
#     "Name": ["Guddiya", "Aman", "Riya", "Rahul", "Neha"],
#     "Age": [22, 23, 21, 20, 21],
#     "Department": ["IT", "HR", "Finance", "IT", "HR"],
#     "Marks": [90, 85, 95, 88, 92]
# }

# df = pd.DataFrame(data)

# df.to_excel("sample_data.xlsx", index=False)

# print("Excel file created successfully!")

In [ ]:
df = pd.read_excel("sample_data.xlsx")
print(df)

      Name  Age Department  Marks
0  Guddiya   22         IT     90
1     Aman   23         HR     85
2     Riya   21    Finance     95
3    Rahul   20         IT     88
4     Neha   21         HR     92

In [ ]:
df = pd.read_csv("SupplyChainGHGmissionFactors.csv")
df.head(7)

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
5,111160,Rice Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
6,111191,Oilseed and Grain Combination Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 8 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   2017 NAICS Code                                1016 non-null   int64
 1   2017 NAICS Title                               1016 non-null   str
 2   GHG                                            1016 non-null   str
 3   Unit                                           1016 non-null   str
 4   Supply Chain Emission Factors without Margins  1016 non-null   float64
 5   Margins of Supply Chain Emission Factors       1016 non-null   float64
 6   Supply Chain Emission Factors with Margins     1016 non-null   float64
 7   Reference USEEIO Code                          1016 non-null   str
dtypes: float64(3), int64(1), str(4)
memory usage: 63.6 KB

statistical Summary

In [ ]:
df.describe()

,2017 NAICS Code,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins
count,1016.000000,1016.000000,1016.000000,1016.000000
mean,424917.376969,0.264994,0.016945,0.281898
std,164942.113495,0.314768,0.023367,0.321417
min,111110.000000,0.026000,0.000000,0.029000
25%,325588.250000,0.103000,0.000000,0.108000
50%,423700.000000,0.159000,0.000000,0.173000
75%,532111.250000,0.302250,0.030250,0.329250
max,813990.000000,3.846000,0.125000,3.924000

3.Average(mean)

In [ ]:
df["Supply Chain Emission Factors without Margins"].mean()

np.float64(0.264994094488189)

Median

In [ ]:
df["Supply Chain Emission Factors without Margins"].median()

np.float64(0.159)

Maximum

In [ ]:
df["Supply Chain Emission Factors without Margins"].max()

np.float64(3.924)

Minimum

In [ ]:
df["Supply Chain Emission Factors without Margins"].min()

np.float64(0.026)

sum

In [ ]:
df["Supply Chain Emission Factors without Margins"].sum()

np.float64(269.23400000000004)

Count

In [ ]:
df["Supply Chain Emission Factors without Margins"].count()

np.int64(1016)

Standard Deviation
Measures how spred out the Margins of Supply Chain Emission Factors are.

In [ ]:
df["Supply Chain Emission Factors without Margins"].std()

np.float64(0.31476825780679674)

Variance

In [ ]:
df["Margins of Supply Chain Emission Factors"]

0       0.044
1       0.044
2       0.040
3       0.040
4       0.040
        ...
1011    0.000
1012    0.000
1013    0.000
1014    0.000
1015    0.000
Name: Margins of Supply Chain Emission Factors, Length: 1016, dtype: float64

count Unique Values

In [ ]:
df["Margins of Supply Chain Emission Factors"].nunique()

69

Frequency Count

In [ ]:
df["Margins of Supply Chain Emission Factors"].value_counts(dropna=False)

Margins of Supply Chain Emission Factors
0.000    562
0.040     22
0.027     22
0.021     20
0.037     18
        ...
0.011      1
0.008      1
0.064      1
0.039      1
0.035      1
Name: count, Length: 69, dtype: int64