A Series is a one_dimensional labled Array

In [2]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

Creating a series with custom Index

In [3]:
import pandas as pd

s=pd.Series([90,85,95], index = ["Math","Science","English"])
print(s)

Math       90
Science    85
English    95
dtype: int64

Acess data:

In [4]:
print(s["Math"])

90

A DataFram is a 2-dimensional table (rows and columns)

In [48]:
# Create a DataFrame

import pandas as pd

data = {

   "Name":["Guddiya","Aman","Riya"],
   "Age":[22,23,21],
   "city":["Delhi","Mumbai","Pune"]
}
df = pd.DataFrame(data)
print(df)

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [7]:
# Access a column

print(df["Name"])

0    Guddiya
1       Aman
2       Riya
Name: Name, dtype: str

In [9]:
# Access rows

# Using.loc[]

print(df.loc[0])

Name    Guddiya
Age          22
city      Delhi
Name: 0, dtype: object

In [11]:
# Using .iloc[]
print(df.iloc[1])

Name      Aman
Age         23
city    Mumbai
Name: 1, dtype: object

Basic Information

In [12]:
print(df.head())

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [13]:
print(df.tail())

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [14]:
print(df.shape)

(3, 3)

In [15]:
print(df.columns)

Index(['Name', 'Age', 'city'], dtype='str')

In [16]:
print(df.dtypes)

Name      str
Age     int64
city      str
dtype: object

In [2]:
# Series
## A panda series is a 1_diemensional array like object that can hold any data 
import pandas as pd
 
data =[1,2,3,4,5] 
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
## Create a series from dictionary
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [1,2,3,4,5]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [47]:
# DataFrame
## create a dataFrame from a Dictionary

data={
    "Name":['krish','jhon','jack'],
     "Age":[20,25,30],
     "city":['Ranchi',"Delhi","pune"]
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    city
0  krish   20  Ranchi
1   jhon   25   Delhi
2   jack   30    pune
<class 'pandas.DataFrame'>

In [4]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.head(5))

   Order_ID  Order_Date        Category   Price  Quantity  Customer_Rating  \
0  ORD-1000  2025-01-01        Clothing  352.10         1              4.0
1  ORD-1001  2025-01-02             NaN  272.69         2              4.0
2  ORD-1002  2025-01-03  Home & Kitchen  161.67         3              1.0
3  ORD-1003  2025-01-04        Clothing  408.76         2              3.0
4  ORD-1004  2025-01-05     Electronics  345.52         3              4.0

     Payment_Method
0  Cash on Delivery
1               UPI
2               UPI
3               UPI
4  Cash on Delivery

In [16]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.tail(5))

     Order_ID  Order_Date     Category   Price  Quantity  Customer_Rating  \
495  ORD-1495  2026-05-11     Clothing   54.88         2              4.0
496  ORD-1496  2026-05-12     Clothing  459.48         2              NaN
497  ORD-1497  2026-05-13  Electronics   77.04         1              2.0
498  ORD-1498  2026-05-14          NaN  475.62         1              2.0
499  ORD-1499  2026-05-15          NaN  228.54         3              3.0

       Payment_Method
495       Credit Card
496               UPI
497  Cash on Delivery
498       Credit Card
499       Credit Card

In [5]:
# Accessing Data From DataFrame 
data

{'Name': ['krish', 'jhon', 'jack'],
 'Age': ['20', '25', '30'],
 'city': ['Ranchi', 'Delhi', 'pune']}

In [10]:
type(df['Name'])
df['Name']

0    krish
1     jhon
2     jack
Name: Name, dtype: str

In [11]:
df.loc[0]

Name     krish
Age         20
city    Ranchi
Name: 0, dtype: str

In [17]:
df.iloc[1]

Name     jhon
Age        25
city    Delhi
Name: 1, dtype: str

In [20]:
## Accessing a specified element
df.at[2,'Age']

'30'

In [21]:
df.at[1,'Name']

'jhon'

In [49]:
## Data manipulation with DataFram
df

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [50]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

      Name  Age    city  Salary
0  Guddiya   22   Delhi   50000
1     Aman   23  Mumbai   60000
2     Riya   21    Pune   70000

In [51]:
## Remove a column
df.drop("Salary",axis=1,inplace=True)
df

      Name  Age    city
0  Guddiya   22   Delhi
1     Aman   23  Mumbai
2     Riya   21    Pune

In [52]:
## Add age the column 
df['Age']=df['Age']+1
df

      Name  Age    city
0  Guddiya   23   Delhi
1     Aman   24  Mumbai
2     Riya   22    Pune

In [53]:
# If i want to remove row
df.drop([0],inplace=True)
df

   Name  Age    city
1  Aman   24  Mumbai
2  Riya   22    Pune

In [54]:
df=pd.read_csv("ecommerce_orders.csv")
print(df.head(5))
df

   Order_ID  Order_Date        Category   Price  Quantity  Customer_Rating  \
0  ORD-1000  2025-01-01        Clothing  352.10         1              4.0
1  ORD-1001  2025-01-02             NaN  272.69         2              4.0
2  ORD-1002  2025-01-03  Home & Kitchen  161.67         3              1.0
3  ORD-1003  2025-01-04        Clothing  408.76         2              3.0
4  ORD-1004  2025-01-05     Electronics  345.52         3              4.0

     Payment_Method
0  Cash on Delivery
1               UPI
2               UPI
3               UPI
4  Cash on Delivery

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery
...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card

In [59]:
# Display the data types of each column
print("Data types \n:",df.dtypes)

# Discribe the DataFrame
print("Statistical summary:\n", df.describe())
# Group by a column and perform aggregation
grouped = df.groupby('Category')['Value'].mean()
print("Mean value by category\n:",grouped)

Data types
: Order_ID               str
Order_Date             str
Category               str
Price              float64
Quantity             int64
Customer_Rating    float64
Payment_Method         str
dtype: object
Statistical summary:
             Price    Quantity  Customer_Rating
count  494.000000  500.000000       457.000000
mean   246.424777    3.092000         3.619256
std    139.640181   10.748702         1.111888
min     12.270000    1.000000         1.000000
25%    122.555000    1.000000         3.000000
50%    241.775000    2.000000         4.000000
75%    365.600000    3.000000         4.000000
max    499.860000  100.000000         5.000000

KeyError: 'Column not found: Value'

In [1]:
import pandas as pd

data1 = {
    "Name":["Guddiya","Aman","Riya","Rahul"],
    "Age":[22,23,21,24],
    "Marks":[90,85,95,80],
    "City":["Delhi","Mumbai","Pune","Delhi"]
}
df = pd.DataFrame(data1)
df

      Name  Age  Marks    City
0  Guddiya   22     90   Delhi
1     Aman   23     85  Mumbai
2     Riya   21     95    Pune
3    Rahul   24     80   Delhi

In [2]:
# Select column

print(df[["Name"]])

      Name
0  Guddiya
1     Aman
2     Riya
3    Rahul

In [3]:
# 2. Select Multiple Columns
print(df[["Name","Marks"]])

      Name  Marks
0  Guddiya     90
1     Aman     85
2     Riya     95
3    Rahul     80

In [4]:
# 3.Add a New column
df["Passed"]=True
df

      Name  Age  Marks    City  Passed
0  Guddiya   22     90   Delhi    True
1     Aman   23     85  Mumbai    True
2     Riya   21     95    Pune    True
3    Rahul   24     80   Delhi    True

In [5]:
# 4. Update a Column

# INcrease everyday's age by 1
df["Age"]+=1
df

      Name  Age  Marks    City  Passed
0  Guddiya   23     90   Delhi    True
1     Aman   24     85  Mumbai    True
2     Riya   22     95    Pune    True
3    Rahul   25     80   Delhi    True

In [6]:
# Delete Column
df.drop("City",axis=1,inplace=True)
df

      Name  Age  Marks  Passed
0  Guddiya   23     90    True
1     Aman   24     85    True
2     Riya   22     95    True
3    Rahul   25     80    True

In [7]:
# Delete a Row
# Delete row with index 2.

df.drop(2, axis=0, inplace=True)
df

      Name  Age  Marks  Passed
0  Guddiya   23     90    True
1     Aman   24     85    True
3    Rahul   25     80    True

In [8]:
# 7.Rename columns
df.rename(columns ={ "Marks":"Scores"}, inplace = True)
df

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

In [9]:
# Filter Data
# Students with marks greater then 85.

print(df[df["Scores"] > 85])

      Name  Age  Scores  Passed
0  Guddiya   23      90    True

In [ ]:
#9.
#  Multiple conditions

print(df[(df["Scores"] > 80) & (df["Name"] == "Guddiya")])

      Name  Age  Scores  Passed
0  Guddiya   23      90    True

10. Short Data

In [13]:
# Accending
print(df.sort_values(by="Scores"))

      Name  Age  Scores  Passed
3    Rahul   25      80    True
1     Aman   24      85    True
0  Guddiya   23      90    True

In [17]:
# Descending order

print(df.sort_values(by="Scores",ascending=False))

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

11. Find Missing values

In [19]:
print(df.isnull())

    Name    Age  Scores  Passed
0  False  False   False   False
1  False  False   False   False
3  False  False   False   False

In [20]:
print(df.isnull().sum())

Name      0
Age       0
Scores    0
Passed    0
dtype: int64

12. Fill Missing Values

In [24]:
# df.fillna(0)

In [26]:
print(df["Scores"].fillna(df["Scores"].mean(),inplace=True))

0    90
1    85
3    80
Name: Scores, dtype: int64

/tmp/ipykernel_4505/3322902417.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  print(df["Scores"].fillna(df["Scores"].mean(),inplace=True))

13. Remove missing value

In [ ]:
# df.dropna()

      Name  Age  Scores  Passed
0  Guddiya   23      90    True
1     Aman   24      85    True
3    Rahul   25      80    True

14. change Data Type

In [31]:
df["Age"]=df["Age"].astype(float)
df

      Name   Age  Scores  Passed
0  Guddiya  23.0      90    True
1     Aman  24.0      85    True
3    Rahul  25.0      80    True

15. Create a new column

In [33]:
df["Bonus"] = df["Scores"]+5
df

      Name   Age  Scores  Passed  Bonus
0  Guddiya  23.0      90    True     95
1     Aman  24.0      85    True     90
3    Rahul  25.0      80    True     85

16. Apply a function

In [36]:
df["Scores"]=df["Scores"].apply(lambda x:x+5)
df

      Name   Age  Scores  Passed  Bonus
0  Guddiya  23.0     100    True     95
1     Aman  24.0      95    True     90
3    Rahul  25.0      90    True     85

17. GROUP DATA
    average marks data

In [41]:
print(df.groupby("Bonus")["Scores"].mean())

Bonus
85     90.0
90     95.0
95    100.0
Name: Scores, dtype: float64

18. Remove Duplicates

In [ ]:
df.drop.duplicates()

19. Reset INdex

In [45]:
print(df.reset_index(drop=True, inplace=True))

None

20. Save DataFrame

In [49]:
#  CSV:

print(df.to_csv("students.csv", index=False))

None

In [ ]:
# Excel:
print(df.to_excel("students.xlsx", index=False))

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ecommerce_orders.csv')
# fetch the five rows
df.head(5)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery

In [4]:
df.tail(5)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card

In [5]:
df.describe()

            Price    Quantity  Customer_Rating
count  494.000000  500.000000       457.000000
mean   246.424777    3.092000         3.619256
std    139.640181   10.748702         1.111888
min     12.270000    1.000000         1.000000
25%    122.555000    1.000000         3.000000
50%    241.775000    2.000000         4.000000
75%    365.600000    3.000000         4.000000
max    499.860000  100.000000         5.000000

In [6]:
df.dtypes

Order_ID               str
Order_Date             str
Category               str
Price              float64
Quantity             int64
Customer_Rating    float64
Payment_Method         str
dtype: object

In [7]:
## Handling Missing value
df.isnull()

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False
496,False,False,False,False,False,True,False
497,False,False,False,False,False,False,False
498,False,False,True,False,False,False,False
499,False,False,True,False,False,False,False

In [8]:
df[df.isnull()]

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().any(axis=1)

0      False
1       True
2      False
3      False
4      False
       ...
495    False
496     True
497    False
498     True
499     True
Length: 500, dtype: bool

In [10]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Category           29
Price               6
Quantity            0
Customer_Rating    43
Payment_Method      0
dtype: int64

In [11]:
df.fillna(0)

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery
1,ORD-1001,2025-01-02,0,272.69,2,4.0,UPI
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery
...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card
496,ORD-1496,2026-05-12,Clothing,459.48,2,0.0,UPI
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery
498,ORD-1498,2026-05-14,0,475.62,1,2.0,Credit Card
499,ORD-1499,2026-05-15,0,228.54,3,3.0,Credit Card

Filling missing value with mean of the column

In [12]:
df['Customer_FiLLna']=df['Customer_Rating'].fillna(df['Customer_Rating'].mean())
df

,Order_ID,Order_Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.000000
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.000000
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.000000
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.000000
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.000000
...,...,...,...,...,...,...,...,...
495,ORD-1495,2026-05-11,Clothing,54.88,2,4.0,Credit Card,4.000000
496,ORD-1496,2026-05-12,Clothing,459.48,2,NaN,UPI,3.619256
497,ORD-1497,2026-05-13,Electronics,77.04,1,2.0,Cash on Delivery,2.000000
498,ORD-1498,2026-05-14,NaN,475.62,1,2.0,Credit Card,2.000000
499,ORD-1499,2026-05-15,NaN,228.54,3,3.0,Credit Card,3.000000

In [13]:

# Renaming columns

df = df.rename(columns={'Order_Date':'Sales Date'})
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0

In [14]:
## Change datatypes
df['Quantity_new']=df['Quantity'].astype(float)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0

In [15]:
# df['Quantity_new'] =df['Quantity'].fillna(df['Quantity'].mean()).astype(int)
df['Quantity_new']=df['Quantity'].astype(float)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0

In [19]:
df['New_Price'] = df['Price'].apply(lambda x:x*2)
df.head()

,Order_ID,Sales Date,Category,Price,Quantity,Customer_Rating,Payment_Method,Customer_FiLLna,Quantity_new,New_Order_ID,New_Price
0,ORD-1000,2025-01-01,Clothing,352.10,1,4.0,Cash on Delivery,4.0,1.0,ORD-1000ORD-1000,704.20
1,ORD-1001,2025-01-02,NaN,272.69,2,4.0,UPI,4.0,2.0,ORD-1001ORD-1001,545.38
2,ORD-1002,2025-01-03,Home & Kitchen,161.67,3,1.0,UPI,1.0,3.0,ORD-1002ORD-1002,323.34
3,ORD-1003,2025-01-04,Clothing,408.76,2,3.0,UPI,3.0,2.0,ORD-1003ORD-1003,817.52
4,ORD-1004,2025-01-05,Electronics,345.52,3,4.0,Cash on Delivery,4.0,3.0,ORD-1004ORD-1004,691.04

In [20]:
grouped_mean = df.groupby('Category')['Price'].mean()
print(grouped_mean)

Category
Books             234.104800
Clothing          256.360662
Electronics       238.445000
Home & Kitchen    254.265392
Name: Price, dtype: float64

In [22]:
grouped_sum = df.groupby(['Category','Order_ID'])['Price'].sum()
print(grouped_sum)

Category        Order_ID
Books           ORD-1007    413.04
                ORD-1033    282.16
                ORD-1035    472.94
                ORD-1043    339.13
                ORD-1052    280.43
                             ...
Home & Kitchen  ORD-1462    130.22
                ORD-1480    173.78
                ORD-1481    387.75
                ORD-1483     46.82
                ORD-1491    350.40
Name: Price, Length: 469, dtype: float64

In [23]:
## Aggregate multiple function
grouped_agg = df.groupby('Order_ID')['Price'].agg(['mean','sum','count'])
print(grouped_agg)

            mean     sum  count
Order_ID
ORD-1000  352.10  352.10      1
ORD-1001  272.69  272.69      1
ORD-1002  161.67  161.67      1
ORD-1003  408.76  408.76      1
ORD-1004  345.52  345.52      1
...          ...     ...    ...
ORD-1495   54.88   54.88      1
ORD-1496  459.48  459.48      1
ORD-1497   77.04   77.04      1
ORD-1498  475.62  475.62      1
ORD-1499  228.54  228.54      1

[498 rows x 3 columns]

In [25]:
# Merging and joining Dataframes
# Create sample DataFrames

df1 = pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','C'],'Vale2':[4,5,6]})

In [26]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [27]:
df2

  key  Vale2
0   A      4
1   B      5
2   C      6

* Aggrigate functions

In [3]:
import pandas as pd

data = {
    'Name':["Guddiya","Aman","Rahul","Riya"],
    'Marks':[90,85,95,80],
    'Age':[21,23,22,24]
}
df = pd.DataFrame(data)
print(df)

      Name  Marks  Age
0  Guddiya     90   21
1     Aman     85   23
2    Rahul     95   22
3     Riya     80   24

In [4]:
# 1. sum
print(df['Marks'].sum())

350

In [5]:
# 2.Mean Average
print(df["Marks"].mean())

87.5

In [6]:
# 3.Maximum
print(df["Marks"].max())

95

In [7]:
# 4.Minimum
print(df["Marks"].min())

80

In [8]:
#5.count
print(df["Marks"].count())

4

In [9]:
# 6. Standard Deviation
# measures how spread out the values are.
print(df["Marks"].std())

6.454972243679028

In [10]:
# 7. Variance

print(df["Marks"].var())

41.666666666666664

In [11]:
# 8.Median
# The middle value after sorting
print(df["Marks"].median())

87.5

In [12]:
# 9.Mode
# The most frequently occuring value.
print(df["Marks"].mode())

0    80
1    85
2    90
3    95
Name: Marks, dtype: int64

In [13]:
marks = [80,90,90,85]
print(pd.Series(marks).mode())

0    90
dtype: int64

In [14]:
# 10. Multiple aggrigret Function

print(df['Marks'].agg(['sum','mean','max','min']))

sum     350.0
mean     87.5
max      95.0
min      80.0
Name: Marks, dtype: float64

Agrrigrant functios with groupby()

In [15]:
data = {
    "Department": ['IT','IT','HR','HR'],
    "Salary":[400000,450000,50000,4500]
}

df = pd.DataFrame(data)
print(df)

  Department  Salary
0         IT  400000
1         IT  450000
2         HR   50000
3         HR    4500

In [16]:
# Average Salary by depatment
print(df.groupby('Department')['Salary'].mean())

Department
HR     27250.0
IT    425000.0
Name: Salary, dtype: float64

In [17]:
#  Multiple Aggregate Functions
print(df.groupby('Department')['Salary'].agg(["mean","sum","max","min"]))

                mean     sum     max     min
Department
HR           27250.0   54500   50000    4500
IT          425000.0  850000  450000  400000

In [18]:
#  described() uses Aggregate functions
print(df.describe())

              Salary
count       4.000000
mean   226125.000000
std    231293.599494
min      4500.000000
25%     38625.000000
50%    225000.000000
75%    412500.000000
max    450000.000000